export const TIMEZONES = [
    { timezone: "UTC-12", name: "Baker Island" },
    { timezone: "UTC-11", name: "Midway Island, Niue, Pago Pago" },
    { timezone: "UTC-10", name: "Hawaii-Aleutian, Hawaii" },
    { timezone: "UTC-09:30", name: "Marquesas Islands" },
    { timezone: "UTC-09", name: "Gambier Islands, Alaska" },
    { timezone: "UTC-08", name: "Pacific Time (US & Canada), Pitcairn Islands" },
    { timezone: "UTC-07", name: "Mountain Time (US & Canada), Arizona" },
    { timezone: "UTC-06", name: "Central Time (US & Canada), Easter Island" },
    { timezone: "UTC-05", name: "Eastern Time (US & Canada), Cuba" },
    { timezone: "UTC-04:30", name: "Caracas" },
    { timezone: "UTC-04", name: "Santiago, La Paz, Falkland Islands, Asuncion" },
    { timezone: "UTC-03:30", name: "Newfoundland" },
    { timezone: "UTC-03", name: "Buenos Aires, Brasilia, Montevideo" },
    { timezone: "UTC-02", name: "Mid-Atlantic" },
    { timezone: "UTC-01", name: "Azores, Cape Verde Is." },
    { timezone: "UTC+00", name: "UTC, Reykjavik, Ouagadougou" },
    { timezone: "UTC+01", name: "London, Berlin" },
    { timezone: "UTC+02", name: "Helsinki, Kaliningrad, Athens" },
    { timezone: "UTC+03", name: "Moscow, Riyadh, Nairobi" },
    { timezone: "UTC+03:30", name: "Tehran" },
    { timezone: "UTC+04", name: "Dubai, Baku" },
    { timezone: "UTC+04:30", name: "Kabul" },
    { timezone: "UTC+05", name: "Karachi, Yekaterinburg" },
    { timezone: "UTC+05:30", name: "Kolkata, Colombo" },
    { timezone: "UTC+05:45", name: "Kathmandu" },
    { timezone: "UTC+06", name: "Dhaka, Almaty" },
    { timezone: "UTC+06:30", name: "Yangon" },
    { timezone: "UTC+07", name: "Bangkok, Novosibirsk" },
    { timezone: "UTC+08", name: "Hong Kong, Shanghai, Singapore, Perth, Taipei" },
    { timezone: "UTC+09", name: "Tokyo, Seoul" },
    { timezone: "UTC+09:30", name: "Adelaide, Darwin" },
    { timezone: "UTC+10", name: "Sydney, Brisbane, Vladivostok" },
    { timezone: "UTC+10:30", name: "Lord Howe" },
    { timezone: "UTC+11", name: "Noumea, Pohnpei, Magadan" },
    { timezone: "UTC+12", name: "Auckland, Fiji, Wake Island" },
    { timezone: "UTC+12:45", name: "Chatham Islands" },
    { timezone: "UTC+13", name: "Nuku'alofa, Apia" },
    { timezone: "UTC+14", name: "Kiritimati" },
] as const;

export const MAPPING_TIMEZONES = {
    "UTC-12": "UTC-12 | Baker Island",
    "UTC-11": "UTC-11 | Midway Island, Niue, Pago Pago",
    "UTC-10": "UTC-10 | Hawaii-Aleutian, Hawaii",
    "UTC-09:30": "UTC-09:30 | Marquesas Islands",
    "UTC-09": "UTC-09 | Gambier Islands, Alaska",
    "UTC-08": "UTC-08 | Pacific Time (US & Canada), Pitcairn Islands",
    "UTC-07": "UTC-07 | Mountain Time (US & Canada), Arizona",
    "UTC-06": "UTC-06 | Central Time (US & Canada), Easter Island",
    "UTC-05": "UTC-05 | Eastern Time (US & Canada), Cuba",
    "UTC-04:30": "UTC-04:30 | Caracas",
    "UTC-04": "UTC-04 | Santiago, La Paz, Falkland Islands, Asuncion",
    "UTC-03:30": "UTC-03:30 | Newfoundland",
    "UTC-03": "UTC-03 | Buenos Aires, Brasilia, Montevideo",
    "UTC-02": "UTC-02 | Mid-Atlantic",
    "UTC-01": "UTC-01 | Azores, Cape Verde Is.",
    "UTC+00": "UTC+00 | UTC, Reykjavik, Ouagadougou",
    "UTC+01": "UTC+01 | London, Berlin",
    "UTC+02": "UTC+02 | Helsinki, Kaliningrad, Athens",
    "UTC+03": "UTC+03 | Moscow, Riyadh, Nairobi",
    "UTC+03:30": "UTC+03:30 | Tehran",
    "UTC+04": "UTC+04 | Dubai, Baku",
    "UTC+04:30": "UTC+04:30 | Kabul",
    "UTC+05": "UTC+05 | Karachi, Yekaterinburg",
    "UTC+05:30": "UTC+05:30 | Kolkata, Colombo",
    "UTC+05:45": "UTC+05:45 | Kathmandu",
    "UTC+06": "UTC+06 | Dhaka, Almaty",
    "UTC+06:30": "UTC+06:30 | Yangon",
    "UTC+07": "UTC+07 | Bangkok, Novosibirsk",
    "UTC+08": "UTC+08 | Hong Kong, Shanghai, Singapore, Perth, Taipei",
    "UTC+09": "UTC+09 | Tokyo, Seoul",
    "UTC+09:30": "UTC+09:30 | Adelaide, Darwin",
    "UTC+10": "UTC+10 | Sydney, Brisbane, Vladivostok",
    "UTC+10:30": "UTC+10:30 | Lord Howe",
    "UTC+11": "UTC+11 | Noumea, Pohnpei, Magadan",
    "UTC+12": "UTC+12 | Auckland, Fiji, Wake Island",
    "UTC+12:45": "UTC+12:45 | Chatham Islands",
    "UTC+13": "UTC+13 | Nuku'alofa, Apia",
    "UTC+14": "UTC+14 | Kiritimati",
} as const;
