// roles.ts
export const roles = [
    "Director of Human Resources",
    "Software Engineer",
    "Product Manager",
    "Data Scientist",
    "Marketing Specialist",
    "Sales Manager",
    "Customer Support",
    "Business Analyst",
    "UX Designer",
    "Operations Manager",
    "Systems Analyst",
    "Quality Assurance Engineer",
    "Network Administrator",
    "DevOps Engineer",
    "Web Developer",
    "Mobile Developer",
    "Database Administrator",
    "Cloud Architect",
    "Security Analyst",
    "Technical Writer",
    "Project Coordinator",
];
