// roles.ts
export const roles = {
    en: [
        "Executive Director",
        "Country Director",
        "Regional Director",
        "Deputy Director",
        "Chief Operating Officer",
        "Chief Financial Officer",
        "Chief Program Officer",
        "Program Director",
        "Operations Director",
        "Emergency Response Director",
        "Field Director",
        "Area Manager",
        "Regional Manager",
        "Base Manager",
        "Site Manager",
        "Program Manager",
        "Operations Manager",
        "Emergency Response Coordinator",
        "Humanitarian Program Manager",
        "Field Operations Manager",
        "Project Manager",
        "Activity Manager",
        "Camp Manager",
        "WASH Program Manager",
        "Health Program Manager",
        "Education Program Manager",
        "Protection Program Manager",
        "Food Security Manager",
        "Shelter Program Manager",
        "Livelihoods Program Manager",
        "Cash Transfer Program Manager",
        "Nutrition Program Manager",
        "Program Officer",
        "Project Officer",
        "Protection Officer",
        "Child Protection Specialist",
        "Gender-Based Violence Prevention Officer",
        "Public Health Officer",
        "WASH Officer",
        "Education Officer",
        "Livelihoods Officer",
        "Food Security Officer",
        "Nutrition Officer",
        "Mental Health and Psychosocial Support Specialist",
        "Field Coordinator",
        "Field Officer",
        "Field Assistant",
        "Site Coordinator",
        "Community Mobilizer",
        "Outreach Worker",
        "Community Liaison Officer",
        "Mobile Team Leader",
        "Beneficiary Support Officer",
        "Case Worker",
        "Social Worker",
        "Registration Manager",
        "Registration Officer",
        "Registration Assistant",
        "Data Entry Clerk",
        "Identity Verification Officer",
        "Documentation Officer",
        "Documentation Assistant",
        "Biometric Data Collector",
        "Case Management Officer",
        "Logistics Manager",
        "Distribution Manager",
        "Distribution Officer",
        "Distribution Assistant",
        "Warehouse Manager",
        "Warehouse Supervisor",
        "Warehouse Assistant",
        "Supply Chain Coordinator",
        "Procurement Officer",
        "Inventory Control Officer",
        "Stock Keeper",
        "Transport Manager",
        "Transport Officer",
        "Driver",
        "Commodity Distribution Officer",
        "Medical Director",
        "Medical Coordinator",
        "Medical Officer",
        "Doctor",
        "Nurse",
        "Midwife",
        "Pharmacist",
        "Laboratory Technician",
        "Health Educator",
        "Community Health Worker",
        "Epidemiologist",
        "Medical Logistics Officer",
        "WASH Coordinator",
        "WASH Engineer",
        "Water Systems Technician",
        "Sanitation Specialist",
        "Hygiene Promotion Officer",
        "Environmental Health Officer",
        "WASH Assistant",
        "Emergency Response Manager",
        "Emergency Response Coordinator",
        "Disaster Relief Specialist",
        "Emergency Logistics Coordinator",
        "Search and Rescue Coordinator",
        "Emergency Communications Officer",
        "Rapid Response Team Leader",
        "Security Manager",
        "Security Coordinator",
        "Security Officer",
        "Security Guard",
        "Safety Officer",
        "Access Control Officer",
        "Facility Supervisor",
        "Finance Manager",
        "Finance Officer",
        "Accountant",
        "Budget Officer",
        "Financial Controller",
        "Grants Manager",
        "Administrative Manager",
        "Administrative Officer",
        "Administrative Assistant",
        "Human Resources Manager",
        "HR Officer",
        "Payroll Officer",
        "Office Manager",
        "Reception Officer",
        "Monitoring & Evaluation Manager",
        "M&E Officer",
        "Data Manager",
        "Database Manager",
        "Data Collection Officer",
        "Data Analyst",
        "Survey Enumerator",
        "Research Officer",
        "Monitoring Assistant",
        "Reporting Officer",
        "Information Management Officer",
        "Communications Manager",
        "Communications Officer",
        "Public Information Officer",
        "Media Relations Officer",
        "Advocacy Officer",
        "Community Relations Officer",
        "External Relations Officer",
        "Technical Advisor",
        "Engineering Manager",
        "Civil Engineer",
        "Electrical Engineer",
        "IT Manager",
        "IT Officer",
        "GIS Specialist",
        "Construction Manager",
        "Maintenance Officer",
        "Generator Operator",
        "Cleaner",
        "Cook",
        "Maintenance Worker",
        "Gardener/Groundskeeper",
        "Translator/Interpreter",
        "Cultural Advisor",
        "Filing Clerk",
        "Document Controller",
        "Scheduler/Appointment Coordinator",
        "Senior Consultant",
        "Technical Consultant",
        "Evaluation Consultant",
        "Training Consultant",
        "Interim Manager",
        "Temporary Staff",
        "Volunteer Coordinator",
        "Intern",
    ],
    es: [
        "Director Ejecutivo",
        "Director de País",
        "Director Regional",
        "Subdirector",
        "Director de Operaciones",
        "Director Financiero",
        "Director de Programas",
        "Director de Programa",
        "Director de Operaciones",
        "Director de Respuesta a Emergencias",
        "Director de Campo",
        "Gerente de Área",
        "Gerente Regional",
        "Gerente de Base",
        "Gerente de Sitio",
        "Gerente de Programa",
        "Gerente de Operaciones",
        "Coordinador de Respuesta a Emergencias",
        "Gerente de Programa Humanitario",
        "Gerente de Operaciones de Campo",
        "Gerente de Proyecto",
        "Gerente de Actividad",
        "Gerente de Campamento",
        "Gerente de Programa WASH",
        "Gerente de Programa de Salud",
        "Gerente de Programa de Educación",
        "Gerente de Programa de Protección",
        "Gerente de Seguridad Alimentaria",
        "Gerente de Programa de Refugio",
        "Gerente de Programa de Medios de Vida",
        "Gerente de Programa de Transferencia de Efectivo",
        "Gerente de Programa de Nutrición",
        "Oficial de Programa",
        "Oficial de Proyecto",
        "Oficial de Protección",
        "Especialista en Protección Infantil",
        "Oficial de Prevención de Violencia de Género",
        "Oficial de Salud Pública",
        "Oficial de WASH",
        "Oficial de Educación",
        "Oficial de Medios de Vida",
        "Oficial de Seguridad Alimentaria",
        "Oficial de Nutrición",
        "Especialista en Salud Mental y Apoyo Psicosocial",
        "Coordinador de Campo",
        "Oficial de Campo",
        "Asistente de Campo",
        "Coordinador de Sitio",
        "Movilizador Comunitario",
        "Trabajador de Alcance Comunitario",
        "Oficial de Enlace Comunitario",
        "Líder de Equipo Móvil",
        "Oficial de Apoyo al Beneficiario",
        "Trabajador de Caso",
        "Trabajador Social",
        "Gerente de Registro",
        "Oficial de Registro",
        "Asistente de Registro",
        "Digitador de Datos",
        "Oficial de Verificación de Identidad",
        "Oficial de Documentación",
        "Asistente de Documentación",
        "Recolector de Datos Biométricos",
        "Oficial de Gestión de Casos",
        "Gerente de Logística",
        "Gerente de Distribución",
        "Oficial de Distribución",
        "Asistente de Distribución",
        "Gerente de Almacén",
        "Supervisor de Almacén",
        "Asistente de Almacén",
        "Coordinador de Cadena de Suministro",
        "Oficial de Adquisiciones",
        "Oficial de Control de Inventario",
        "Encargado de Almacén",
        "Gerente de Transporte",
        "Oficial de Transporte",
        "Conductor",
        "Oficial de Distribución de Productos",
        "Director Médico",
        "Coordinador Médico",
        "Oficial Médico",
        "Médico",
        "Enfermero/a",
        "Partero/a",
        "Farmacéutico/a",
        "Técnico de Laboratorio",
        "Educador de Salud",
        "Trabajador de Salud Comunitario",
        "Epidemiólogo",
        "Oficial de Logística Médica",
        "Coordinador de WASH",
        "Ingeniero de WASH",
        "Técnico de Sistemas de Agua",
        "Especialista en Saneamiento",
        "Oficial de Promoción de Higiene",
        "Oficial de Salud Ambiental",
        "Asistente de WASH",
        "Gerente de Respuesta a Emergencias",
        "Coordinador de Respuesta a Emergencias",
        "Especialista en Ayuda en Desastres",
        "Coordinador de Logística de Emergencia",
        "Coordinador de Búsqueda y Rescate",
        "Oficial de Comunicaciones de Emergencia",
        "Líder de Equipo de Respuesta Rápida",
        "Gerente de Seguridad",
        "Coordinador de Seguridad",
        "Oficial de Seguridad",
        "Guardia de Seguridad",
        "Oficial de Seguridad",
        "Oficial de Control de Acceso",
        "Supervisor de Instalaciones",
        "Gerente Financiero",
        "Oficial de Finanzas",
        "Contador/a",
        "Oficial de Presupuesto",
        "Controlador Financiero",
        "Gerente de Subvenciones",
        "Gerente Administrativo",
        "Oficial Administrativo",
        "Asistente Administrativo",
        "Gerente de Recursos Humanos",
        "Oficial de RRHH",
        "Oficial de Nómina",
        "Gerente de Oficina",
        "Oficial de Recepción",
        "Gerente de Monitoreo y Evaluación",
        "Oficial de M&E",
        "Gerente de Datos",
        "Gerente de Base de Datos",
        "Oficial de Recolección de Datos",
        "Analista de Datos",
        "Encuestador",
        "Oficial de Investigación",
        "Asistente de Monitoreo",
        "Oficial de Informes",
        "Oficial de Gestión de la Información",
        "Gerente de Comunicaciones",
        "Oficial de Comunicaciones",
        "Oficial de Información Pública",
        "Oficial de Relaciones con los Medios",
        "Oficial de Incidencia",
        "Oficial de Relaciones Comunitarias",
        "Oficial de Relaciones Externas",
        "Asesor Técnico",
        "Gerente de Ingeniería",
        "Ingeniero Civil",
        "Ingeniero Eléctrico",
        "Gerente de TI",
        "Oficial de TI",
        "Especialista en SIG",
        "Gerente de Construcción",
        "Oficial de Mantenimiento",
        "Operador de Generador",
        "Limpiador/a",
        "Cocinero/a",
        "Trabajador de Mantenimiento",
        "Jardinero/a",
        "Traductor/Intérprete",
        "Asesor Cultural",
        "Archivista",
        "Controlador de Documentos",
        "Coordinador de Citas/Programación",
        "Consultor Senior",
        "Consultor Técnico",
        "Consultor de Evaluación",
        "Consultor de Capacitación",
        "Gerente Interino",
        "Personal Temporal",
        "Coordenador de Voluntarios",
        "Intern",
    ],
    pt: [
        "Diretor Executivo",
        "Diretor de País",
        "Diretor Regional",
        "Diretor Adjunto",
        "Chefe de Operações",
        "Diretor Financeiro",
        "Diretor de Programas",
        "Diretor de Programa",
        "Diretor de Operações",
        "Diretor de Resposta a Emergências",
        "Diretor de Campo",
        "Gerente de Área",
        "Gerente Regional",
        "Gerente de Base",
        "Gerente de Site",
        "Gerente de Programa",
        "Gerente de Operações",
        "Coordenador de Resposta a Emergências",
        "Gerente de Programa Humanitário",
        "Gerente de Operações de Campo",
        "Gerente de Projeto",
        "Gerente de Atividades",
        "Gerente de Acampamento",
        "Gerente de Programa WASH",
        "Gerente de Programa de Saúde",
        "Gerente de Programa de Educação",
        "Gerente de Programa de Proteção",
        "Gerente de Segurança Alimentar",
        "Gerente de Programa de Abrigo",
        "Gerente de Programa de Meios de Subsistência",
        "Gerente de Programa de Transferência de Dinheiro",
        "Gerente de Programa de Nutrição",
        "Oficial de Programa",
        "Oficial de Projeto",
        "Oficial de Proteção",
        "Especialista em Proteção Infantil",
        "Oficial de Prevenção de Violência de Gênero",
        "Oficial de Saúde Pública",
        "Oficial WASH",
        "Oficial de Educação",
        "Oficial de Meios de Subsistência",
        "Oficial de Segurança Alimentar",
        "Oficial de Nutrição",
        "Especialista em Saúde Mental e Apoio Psicossocial",
        "Coordenador de Campo",
        "Oficial de Campo",
        "Assistente de Campo",
        "Coordenador de Site",
        "Mobilizador Comunitário",
        "Trabalhador de Extensão Comunitária",
        "Oficial de Ligação Comunitária",
        "Líder de Equipe Móvel",
        "Oficial de Apoio ao Beneficiário",
        "Assistente Social",
        "Assistente Social",
        "Gerente de Registro",
        "Oficial de Registro",
        "Assistente de Registro",
        "Digitador",
        "Oficial de Verificação de Identidade",
        "Oficial de Documentação",
        "Assistente de Documentação",
        "Coletor de Dados Biométricos",
        "Oficial de Gestão de Casos",
        "Gerente de Logística",
        "Gerente de Distribuição",
        "Oficial de Distribuição",
        "Assistente de Distribuição",
        "Gerente de Armazém",
        "Supervisor de Armazém",
        "Assistente de Armazém",
        "Coordenador da Cadeia de Suprimentos",
        "Oficial de Compras",
        "Oficial de Controle de Estoque",
        "Encarregado de Estoque",
        "Gerente de Transporte",
        "Oficial de Transporte",
        "Motorista",
        "Oficial de Distribuição de Mercadorias",
        "Diretor Médico",
        "Coordenador Médico",
        "Oficial Médico",
        "Médico/a",
        "Enfermeiro/a",
        "Parteiro/a",
        "Farmacêutico/a",
        "Técnico de Laboratório",
        "Educador de Saúde",
        "Agente Comunitário de Saúde",
        "Epidemiologista",
        "Oficial de Logística Médica",
        "Coordenador WASH",
        "Engenheiro WASH",
        "Técnico de Sistemas de Água",
        "Especialista em Saneamento",
        "Oficial de Promoção de Higiene",
        "Oficial de Saúde Ambiental",
        "Assistente WASH",
        "Gerente de Resposta a Emergências",
        "Coordenador de Resposta a Emergências",
        "Especialista em Socorro a Desastres",
        "Coordenador de Logística de Emergência",
        "Coordenador de Busca e Salvamento",
        "Oficial de Comunicações de Emergência",
        "Líder de Equipe de Resposta Rápida",
        "Gerente de Segurança",
        "Coordenador de Segurança",
        "Oficial de Segurança",
        "Guarda de Segurança",
        "Oficial de Segurança",
        "Oficial de Controle de Acesso",
        "Supervisor de Instalações",
        "Gerente Financeiro",
        "Oficial de Finanças",
        "Contador/a",
        "Oficial de Orçamento",
        "Controlador Financeiro",
        "Gerente de Subsídios",
        "Gerente Administrativo",
        "Oficial Administrativo",
        "Assistente Administrativo",
        "Gerente de Recursos Humanos",
        "Oficial de RH",
        "Oficial de Folha de Pagamento",
        "Gerente de Escritório",
        "Recepcionista",
        "Gerente de Monitoramento e Avaliação",
        "Oficial de M&A",
        "Gerente de Dados",
        "Gerente de Banco de Dados",
        "Oficial de Coleta de Dados",
        "Analista de Dados",
        "Entrevistador",
        "Oficial de Pesquisa",
        "Assistente de Monitoramento",
        "Oficial de Relatórios",
        "Oficial de Gestão da Informação",
        "Gerente de Comunicações",
        "Oficial de Comunicações",
        "Oficial de Informação Pública",
        "Oficial de Relações com a Mídia",
        "Oficial de Advocacia",
        "Oficial de Relações Comunitárias",
        "Oficial de Relações Externas",
        "Consultor Técnico",
        "Gerente de Engenharia",
        "Engenheiro Civil",
        "Engenheiro Elétrico",
        "Gerente de TI",
        "Oficial de TI",
        "Especialista em GIS",
        "Gerente de Construção",
        "Oficial de Manutenção",
        "Operador de Gerador",
        "Limpador/a",
        "Cozinheiro/a",
        "Trabalhador de Manutenção",
        "Jardineiro/a",
        "Tradutor/Intérprete",
        "Consultor Cultural",
        "Arquivista",
        "Controlador de Documentos",
        "Coordenador de Agendamento/Compromissos",
        "Consultor Sênior",
        "Consultor Técnico",
        "Consultor de Avaliação",
        "Consultor de Treinamento",
        "Gerente Interino",
        "Pessoal Temporário",
        "Coordenador de Voluntários",
        "Estagiário/a",
    ],
};
